### ISSUE TITLE
Statically link (or package along) Glibc to libhadoop.so and libsnappy.so

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto-hadoop-apache2#8]
Hi,

Current Presto master requires GlibC to be at least 2.12. However SLES11 and probably some other commercial distros still have GlibC 2.11 or lower. Would you mind if I compile GlibC statically into libhadoop and libsnappy so that no GlibC problems occur?

**Comment by electrum** [comment]
I'm not sure what the implications of that are, especially given that the JVM links to glibc. It appears that the JVM requires version `GLIBC_2.2.5`. I'm guessing you are reporting this because the previous version was built against CentOS 5 but the latest one used CentOS 6.

I did a quick search but didn't see an obvious way to force linking to an older version of glibc, especially with the Hadoop CMake stuff. Probably the easiest way is to rebuild the libraries on a CentOS 5 machine.

**Comment by sopel39** [comment]
I think it should work because in SLES11 Presto works correctly even though GlibC is lower than 2.2.5.
Therefore will you accept pull request with both `libhadoop` and `libsnappy` statically linked with Glibc?

**Comment by electrum** [comment]
The previous one was built on CentOS 5 and worked, so we'll rebuild the libraries with that. We definitely do not want to statically link.

**Comment by sopel39** [comment]
Great, thanks!

**Comment by electrum** [comment]
I found another issue here: the OpenSSL library on CentOS 5 (and likely SLES 11) are too old to be supported by Hadoop's native library. This seems to be fine since it is only used for one crypto codec and there is a fallback JCE version.

**Comment by electrum** [comment]
Fixed in 51c3b435bec7eb0ec3c40523c447375e1949a1f4
